version: "3.9"

services:
  api:
    container_name: vplans-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
      - "9229:9229"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    extra_hosts:
      # host for db connection
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV:development
    restart: unless-stopped
    command: yarn run start:debug
    depends_on:
      - postgres
    env_file:
      - .env

  web:
    container_name: vplans-web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - api

  postgres:
    container_name: vplans-postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pg-admin:
    container_name: vplan-pg-admin
    image: dpage/pgadmin4:7
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    depends_on:
      - postgres
    ports:
      - "5050:5050"

volumes:
  data:
